### ISSUE TITLE
iqm - error in job file

### ISSUE THREAD

**Issue by mbarbry** [votca/xtp#148]
There are some issues in the job_file for `iqm` calculators. It seems to not be written properly.

From `idft` I was getting something like

    <input>
        <segment id="5" type="segMethane">5</segment>
        <segment id="30" type="segMethane">30</segment>
    </input>

but now I'm getting the following,

    <input>
        <segment id="93" type="segMethane">93</segment>
        <segment>93</segment>
    </input>

I get then the following error,

    terminate called after throwing an instance of 'std::runtime_error'
    what():  attribute id not found

Furthermore, as you can notice, the segments are the same in the case of `iqm` which does not make sense.

**Comment by JensWehner** [comment]
yeah it is not yet fully tested.

**Comment by JensWehner** [comment]
on my list

**Comment by JensWehner** [comment]
eqm is fixed in the latest commit. iqm is nearly done.

**Comment by mbarbry** [comment]
Thanks!

**Comment by mbarbry** [comment]
I still get `nan` values for the atomic position (see issue https://github.com/votca/xtp/issues/147) in the nwchem input when running `eqm`

**Comment by mbarbry** [comment]
Related to `iqm`, I think I spot a bug in `src/libxtp/dftcoupling.cc` in `WriteToProperty`. From what I understood, it should be

     coupling.setAttribute("levelA", a);

instead of

    type_summary.setAttribute("levelA", a);

the same applies to `levelB`, `jAB`, `eA` and `eB`

**Comment by JensWehner** [comment]
closed by #152
